jasypt:
  encryptor:
    password: aiot-sunvalley

mqtt:
  tcp-server:
    ip: 0.0.0.0
    port: 9903
    heart-in-second: 60
    tls: true
    log: true
    node-id: 2
  topic:
    prefix-paths:
      - iot/get/
      - iot/update/

debug: true

spring:
  kafka:
    bootstrap-servers: 10.20.0.92:9092
    consumer:
      group-id: ${spring.application.name}_${mqtt.tcp-server.node-id}
      auto-offset-reset: latest