jasypt:
  encryptor:
    password: aiot-sunvalley

mqtt:
  tcp-server:
    ip: 0.0.0.0
    port: 9903
    heart-in-second: 60
    tls: true
    log: true
    node-id: 1
    cert-url: https://aiot-platform.s3-us-west-2.amazonaws.com/dev/ca.crt
    cert-private-key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDQEUk6cn3bZZu1
      E8po4M5oy8yKVukoZ5svpZWK6Uu/SrrC8RPgMqD0wuDegjyX98Z19+HQi8n5pOuk
      nxUStsKKIp1fhiaq2w8zco1ewpQUl7R7wFYIdWr17Q8h2R+kk3GNV/L5mbtgbihi
      krXIeUBkPu4Z9iQA/l13i3E8Vk0WtmMrxP17n+QVGlTvggAa34fiRicElAW1WLVp
      Rl93fZp5EZlrprU25d5F5rPnuKeN4nxL/MbOx8fQL2hLuDdbPfK3ff5wLxFpD6EE
      yQmU6oCObjnX5QS/GBf81c6/D7X7NRCZvNDvbD15BGMWqLd9p4pU1DZ1EpyTjHtB
      YeK/jPLNAgMBAAECggEAUAimK1ZI9TCjcUa4kBkRLJxgBEKkEwevWOePm0xb96wO
      JNhIte+jnCKuDsj399i2PUBpWye6PE3k2oDawUUNlcb00/6tNwFmWnrQyEd+YGFu
      aj+0mDJaP1i9fl6fXlXc0uqmqr4oplIZNLmMNR3219ihC9lzRfKSD17S4surgXVa
      v1jkUibzds5b/Rl+qgjCB7QMbEVGF5cZiyeSgpXGgr7uRJOI4xnyYlwldpnRXSVV
      LlBlT85h9B49hOOoaLLQUcXzFbQI/3brN5GJ9bMzOL65TvkuyRoNk1+6GMnowVoR
      rXL4nuL/ekfcp2VwJZKot+Px9VZzk/+qlQtbNv4j/QKBgQD3DXcf+fY/MS+YrF/f
      TmzPONbdEaYq31evzPM+3F4MLgrVx1bUeUZyECnmb5CTiyhqa1nT6bOB3zSPVO1j
      3ct22n3LgFEwq16S927aTg8NINlu2LieUlg9RIfHj917sDtp88Ovn43l1dbS2tmY
      54gBl7UjvWj1TDa1dV4xAsh+wwKBgQDXml9qqXfJVEuLzCQcWwBNmiFTrJ5Gl9e4
      QbMLtISt68HFM1lBqirRHjkaVf3vUhT3ACG9M+f9PvqwT9SXodnaOov+3Xl/a2fZ
      mJn+dXJ9ENhqTY5B0qrtkD//xBHonNuKcT3Ei+tl6aQLLcivj4EHw2vEGAAAzS1E
      qEyvwOrPLwKBgQClRgHSh4NgJQSFa5O7rRiHzKuZOwxiFAXyWvbDr+LO3SJsf62r
      +PHSrtOJEEu1GNxRzT1L0kU/ddYQqS0iqSdLfMG5GT+3gn2DbjpfmubgzoAHcr6X
      U9kqK6V2MN1nuK8Wo3ffDqt7/YF4j+YQL5xCDH6myTjlGTZkUH9R5F3CxwKBgCg0
      XEiqk3DSrEfEaJN1EMhnzoEo9lbZp9tvPPEY14kLJpYcbi+FiPh391QG5xSCrPAm
      cSQ0ErWx0dOg/1bLUrGUK1j6edad876q60R9KD1UL9ca4UU7AK7OMHEEYgaLgZD+
      bvNA2EOn3vRKtFqwmvIUqfrmMtHzcNaVv78ibWb3AoGBAKpzOVN6q+nrHMNMcMUS
      v1HMlZOhgOKEjX6vH+Qp8H0f24fAb2GLhl4bp7cvrsU6ueHdzImq/YCVY8JgMT07
      e57KubYRoXvXGajNBecBpAlquKHixIwmc08sDMF6MPGr7/CaCiJJSJeRkrxXrGb4
      XA555MZStxhfMFXHsiv2ofSm
      -----END PRIVATE KEY-----
  topic:
    prefix-paths:
      - iot/get/
      - iot/update/

debug: true

spring:
  kafka:
    bootstrap-servers: 10.20.0.92:9092
    consumer:
      group-id: ${spring.application.name}_${mqtt.tcp-server.node-id}
      auto-offset-reset: latest
skip:
  authentication: true