vertx:
  zookeeperHosts: 10.20.0.92
  kafka:
    bootstrapServer: 10.20.0.92:2181

broker:
  topic:
    login: aiot-mqtt-login
    beat: aiot-mqtt-beat
    instruct: aiot-mqtt-instruct

jasypt:
  encryptor:
    password: aiot-sunvalley

logging:
  level:
    com.sunvalley: debug
    mvc.api: debug
    mvc.rmi: debug

