vertx:
  kafka:
    bootstrapServer: 10.20.0.92:9092


event:
  topic:
    login: aiot-event-login_dev
    instruct: aiot-event-instruct_dev

broker:
  topic:
    login: aiot-broker-login_dev
    beat: aiot-broker-beat_dev
    instruct: aiot-broker-instruct_dev

jasypt:
  encryptor:
    password: aiot-sunvalley

logging:
  level:
    com.sunvalley: debug
    mvc.api: debug
    mvc.rmi: debug

mqtt:
  tcp-server:
    ip: localhost
    port: 8084
    heart-in-second: 20
    tls: true
    log: true
